classDiagram
    Shapes <|-- Circle
    Shapes <|-- Line
    Shapes <|-- Rectangle
    Shapes <|-- xxx
    Circle <|-- DiscoKugel
    Line <|-- Leuchtstab

    class Shapes {
        +act()
        +move(double dx, double dy)
        +setFillColor(Color color)
        +rotate(double degrees)
        +scale(double factor)
    }

    class DiscoKugel {
        +DiscoKugel(double x, double y)
        +act()
    }

    class Leuchtstab {
        +Leuchtstab(double x, double y)
        +act()
    }